### ISSUE TITLE
Upgrade to v6 

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.Spring#12]
Related to https://github.com/Particular/NServiceBus/issues/3076

**Comment by petersgiles** [comment]
@mauroservienti 

The acceptance tests pass with the exception of `Transient_component_should_be_destructed_called` that seems to want to ensure the WeakReference is not Alive. I'm not sure what the reasoning is for this test.

There are 2 inconclusive tests `When_doing_request_response_between_sagas : NServiceBusAcceptanceTest` and `When_receiving_that_should_start_a_saga : NServiceBusAcceptanceTest` It's not really clear what these are testing either.

Can some one who understands the context around these tests please explain or complete this issue?

**Comment by johnsimons** [comment]
@SimonCropp it looks like you have done this ?

**Comment by johnsimons** [comment]
This seem to be done

**Comment by mauroservienti** [comment]
Why is this closed with unanswered questions?
Considering that Core is not yet released should we close downstream repo issues that have a dependency on a non stable core?

**Comment by johnsimons** [comment]
I would think so, otherwise how do we show progress ?

If we find any further bugs we can open new issues.

**Comment by mauroservienti** [comment]
Closing not-really-done things just to show progress is not, IMO, the way to go.
Anyway should we raise an issue to track that we need to?

* Wait for Core to be released
* Update this repo to the latest version of Core
* Release

**Comment by johnsimons** [comment]
@mauroservienti since the release of any component will have to tick the list above, I don't see a reason to have an issue for this.
IMO I would put together a list of actions that need to be done before releasing any of nsb dependencies and quite possible nsb core as well. And then I would circulate this list and let the maintainer groups go ahead and follow the steps.

**Comment by SimonCropp** [comment]
Yeah i dont see the point of having an issue in every repo to remind us to update to the final v6

**Comment by mauroservienti** [comment]
So should we leave this open and add the list as check boxes?

**Comment by SimonCropp** [comment]
> i dont see the point of having an issue in every repo

one issue in platform dev will do
