### ISSUE TITLE
Type-based Configure should check for existing registration

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.Spring#3]
Factory-based Configure does this check

```
if (HasComponent(componentType))
{
   return;
}
```

So if a component is registered more than once, subsequent registrations are ignored. Same check needs to be added to type-based configure so that the behavior is consistent with other builders and fixes https://github.com/Particular/NServiceBus/issues/1203.

**Comment by danielmarbach** [comment]
@SzymonPobiega Should we address this as well when the PR #5 is merged or leave it as PR currently is? What is your thoughts @SimonCropp @johnsimons ?

**Comment by SzymonPobiega** [comment]
Did you fixed that in #5 @danielmarbach ?

**Comment by danielmarbach** [comment]
Nope I left this out of scope. Essentially the HasComponent calls are removed now. There wasn't a single ATT ensuring that behavior. Because none failed. How shoul we proceed?

**Comment by danielmarbach** [comment]
@Particular/container-maintainers ping I think we should close this since we do not want to put more effort into the spring container. Any counter arguments?

> 32,768 total downloads

**Comment by SimonCropp** [comment]
@danielmarbach what do u think about marking the root config class with with an obsolete attribute?

**Comment by danielmarbach** [comment]
So completely deprecating it?

**Comment by SimonCropp** [comment]
will there be another major?

**Comment by danielmarbach** [comment]
That's what we have to decide. I would suggest No

**Comment by boblangley** [comment]
I agree. Would this mean we would move it to labs?

**Comment by WilliamBZA** [comment]
> 32,768 total downloads

As much as that number pleases me aesthetically, I agree on ending support for this.

**Comment by HEskandari** [comment]
Think the ["Interest over time"](url) talks louder than words.

**Comment by tmasternak** [comment]
This has been already [solved](https://github.com/Particular/NServiceBus.Spring/commit/02698008bee68187c30fecc17084c27315c424fb#diff-17a5637700bdfa375a758280677dde9b) by @mikeminutillo
